FROM nginx:1.16-alpine
ADD . /code
WORKDIR /code
RUN apk update
RUN apk add --no-cache --virtual .build-deps g++ python3-dev libffi-dev openssl-dev && \
    pip3 install --upgrade pip setuptools && \
    pip3 install -r requirements.txt && \
    apk del .build-deps
RUN apk add --no-cache --update python3

EXPOSE 8001
CMD python manage.py runserver
