FROM nginx:1.16-alpine
ADD . /code
WORKDIR /code
RUN apk update

RUN apk add --no-cache --virtual .build-deps g++ python3-dev libffi-dev openssl-dev curl && \
    pip3 install --upgrade pip setuptools && \
    pip3 install uWSGI && \
    apk del .build-deps

RUN apk add --no-cache --update python3
ENTRYPOINT . entrypoint.sh
EXPOSE 8000
